### ISSUE TITLE
`multipartBody` does not set the boundary in the Content-Type header

### ISSUE THREAD

**Issue by crazymykl** [elm-lang/http#4]
Code to reproduce this can be found here:
https://gist.github.com/crazymykl/3463ceddf89986b46821933b1bc0a11a

When running this program, a POST request is sent with the `Content-Type` header set to `multipart/form-data`. It needs to be set to `multipart/form-data; boundary={the generated delimiter}`.

I chose the Slack API for the SSCCE because it explicitly sends `error: "invalid_form_data`. I would expect this request to instead give `error: "not_authed"`, since we don't send a token.

**Comment by evancz** [comment]
Thanks for the SSCCE and the report and the PR!

I made the fix, so if you delete your `elm-stuff/` and rebuild this should be fixed. Since we are in the alpha phase, I'm not bumping version numbers for every little thing. All of this stuff is unreleased, so 1.0.0 has not *actually* been published yet.
